--- #YAML:1.0
name: cmap
version: 0.12
author: Ken Y. Clark <kclark@cshl.org>
abstract: Genetic and comparative maps
license: gpl
requires:
  Algorithm::Numerical::Sample: 0
  Bit::Vector: 0
  CGI: 0
  Class::Base: 0
  Config::General: 0
  DBI: 1.2
  Data::Page: 0
  Data::Pageset: 0
  Date::Format: 0
  File::Temp: 0
  GD: 2.11
  GD::SVG: 0.25
  Regexp::Common: 0
  Template: 2
  Text::RecordParser: 0.02
  Time::ParseDate: 0
  Time::Piece: 0
  URI::Escape: 0
  XML::Simple: 0
provides:
  Bio::GMOD::CMap:
    file: lib/Bio/GMOD/CMap.pm
    version: 0.12
  Bio::GMOD::CMap::Admin:
    file: lib/Bio/GMOD/CMap/Admin.pm
    version: 1.46.2.5
  Bio::GMOD::CMap::Admin::Export:
    file: lib/Bio/GMOD/CMap/Admin/Export.pm
    version: 1.6.2.2
  Bio::GMOD::CMap::Admin::Import:
    file: lib/Bio/GMOD/CMap/Admin/Import.pm
    version: 1.45.2.2
  Bio::GMOD::CMap::Admin::ImportCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/ImportCorrespondences.pm
    version: 1.16
  Bio::GMOD::CMap::Admin::MakeCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/MakeCorrespondences.pm
    version: 1.29.2.3
  Bio::GMOD::CMap::Apache:
    file: lib/Bio/GMOD/CMap/Apache.pm
    version: 1.16.2.1
  Bio::GMOD::CMap::Apache::AdminViewer:
    file: lib/Bio/GMOD/CMap/Apache/AdminViewer.pm
    version: 1.64
  Bio::GMOD::CMap::Apache::CorrespondenceViewer:
    file: lib/Bio/GMOD/CMap/Apache/CorrespondenceViewer.pm
    version: 1.2
  Bio::GMOD::CMap::Apache::DataDownloader:
    file: lib/Bio/GMOD/CMap/Apache/DataDownloader.pm
    version: 1.1.2.2
  Bio::GMOD::CMap::Apache::EvidenceTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/EvidenceTypeViewer.pm
    version: 1.2.2.1
  Bio::GMOD::CMap::Apache::FeatureAliasViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureAliasViewer.pm
    version: 1.2
  Bio::GMOD::CMap::Apache::FeatureSearch:
    file: lib/Bio/GMOD/CMap/Apache/FeatureSearch.pm
    version: 1.17.2.1
  Bio::GMOD::CMap::Apache::FeatureTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureTypeViewer.pm
    version: 1.6.2.1
  Bio::GMOD::CMap::Apache::FeatureViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureViewer.pm
    version: 1.11
  Bio::GMOD::CMap::Apache::HelpViewer:
    file: lib/Bio/GMOD/CMap/Apache/HelpViewer.pm
    version: 1.13.2.1
  Bio::GMOD::CMap::Apache::Index:
    file: lib/Bio/GMOD/CMap/Apache/Index.pm
    version: 1.8
  Bio::GMOD::CMap::Apache::MapDetailViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapDetailViewer.pm
    version: 1.22.2.1
  Bio::GMOD::CMap::Apache::MapSetViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapSetViewer.pm
    version: 1.14
  Bio::GMOD::CMap::Apache::MapTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapTypeViewer.pm
    version: 1.2.2.1
  Bio::GMOD::CMap::Apache::MapViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapViewer.pm
    version: 1.31.2.1
  Bio::GMOD::CMap::Apache::MatrixViewer:
    file: lib/Bio/GMOD/CMap/Apache/MatrixViewer.pm
    version: 1.10
  Bio::GMOD::CMap::Apache::SpeciesViewer:
    file: lib/Bio/GMOD/CMap/Apache/SpeciesViewer.pm
    version: 1.3.2.1
  Bio::GMOD::CMap::Apache::ViewFeatureOnMap:
    file: lib/Bio/GMOD/CMap/Apache/ViewFeatureOnMap.pm
    version: 1.7.2.2
  Bio::GMOD::CMap::Data:
    file: lib/Bio/GMOD/CMap/Data.pm
    version: 1.98.2.21
  Bio::GMOD::CMap::Data::Generic:
    file: lib/Bio/GMOD/CMap/Data/Generic.pm
    version: 1.46.2.2
  Bio::GMOD::CMap::Data::MySQL:
    file: lib/Bio/GMOD/CMap/Data/MySQL.pm
    version: 1.4
  Bio::GMOD::CMap::Data::Oracle:
    file: lib/Bio/GMOD/CMap/Data/Oracle.pm
    version: 1.6
  Bio::GMOD::CMap::Drawer:
    file: lib/Bio/GMOD/CMap/Drawer.pm
    version: 1.53.2.4
  Bio::GMOD::CMap::Drawer::Map:
    file: lib/Bio/GMOD/CMap/Drawer/Map.pm
    version: 1.70.2.9
  Bio::GMOD::CMap::Utils:
    file: lib/Bio/GMOD/CMap/Utils.pm
    version: 1.25.2.13
generated_by: Module::Build version 0.25
