---
name: cmap
version: 0.15
author:
  - Ken Y. Clark <kclark@cshl.org>
abstract: Genetic and comparative maps
license: gpl
requires:
  Algorithm::Cluster: 0
  Algorithm::Numerical::Sample: 0
  Apache::Htpasswd: 0
  Bit::Vector: 0
  CGI: 0
  CGI::Session: 0
  Cache::FileCache: 0
  Class::Base: 0
  Clone: 0
  Config::General: 0
  DBI: 1.2
  Data::Dumper: 0
  Data::Page: 0
  Data::Pageset: 0
  Data::Stag: 0
  Date::Format: 0
  File::Temp: 0
  Filesys::Df: 0
  GD: 2.11
  GD::SVG: 0.25
  IO::Prompt: 0
  IO::Tee: 0
  Params::Validate: 0
  Regexp::Common: 0
  Storable: 0
  Template: 2
  Text::RecordParser: 0.02
  Time::ParseDate: 0
  Time::Piece: 0
  URI::Escape: 0
  XML::Simple: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Bio::GMOD::CMap:
    file: lib/Bio/GMOD/CMap.pm
    version: 0.15
  Bio::GMOD::CMap::Admin:
    file: lib/Bio/GMOD/CMap/Admin.pm
    version: 1.87
  Bio::GMOD::CMap::Admin::Export:
    file: lib/Bio/GMOD/CMap/Admin/Export.pm
    version: 1.24
  Bio::GMOD::CMap::Admin::GBrowseLiason:
    file: lib/Bio/GMOD/CMap/Admin/GBrowseLiason.pm
    version: 1.10
  Bio::GMOD::CMap::Admin::Import:
    file: lib/Bio/GMOD/CMap/Admin/Import.pm
    version: 1.78
  Bio::GMOD::CMap::Admin::ImportAlignments:
    file: lib/Bio/GMOD/CMap/Admin/ImportAlignments.pm
    version: 1.6
  Bio::GMOD::CMap::Admin::ImportCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/ImportCorrespondences.pm
    version: 1.34
  Bio::GMOD::CMap::Admin::MakeCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/MakeCorrespondences.pm
    version: 1.55
  Bio::GMOD::CMap::Admin::ManageLinks:
    file: lib/Bio/GMOD/CMap/Admin/ManageLinks.pm
    version: 1.9
  Bio::GMOD::CMap::Admin::SavedLink:
    file: lib/Bio/GMOD/CMap/Admin/SavedLink.pm
  Bio::GMOD::CMap::Apache:
    file: lib/Bio/GMOD/CMap/Apache.pm
    version: 1.36
  Bio::GMOD::CMap::Apache::AdminViewer:
    file: lib/Bio/GMOD/CMap/Apache/AdminViewer.pm
    version: 1.91
  Bio::GMOD::CMap::Apache::CorrespondenceViewer:
    file: lib/Bio/GMOD/CMap/Apache/CorrespondenceViewer.pm
    version: 1.4
  Bio::GMOD::CMap::Apache::DataDownloader:
    file: lib/Bio/GMOD/CMap/Apache/DataDownloader.pm
    version: 1.4
  Bio::GMOD::CMap::Apache::EvidenceTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/EvidenceTypeViewer.pm
    version: 1.8
  Bio::GMOD::CMap::Apache::FeatureAliasViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureAliasViewer.pm
    version: 1.5
  Bio::GMOD::CMap::Apache::FeatureSearch:
    file: lib/Bio/GMOD/CMap/Apache/FeatureSearch.pm
    version: 1.23
  Bio::GMOD::CMap::Apache::FeatureTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureTypeViewer.pm
    version: 1.12
  Bio::GMOD::CMap::Apache::FeatureViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureViewer.pm
    version: 1.15
  Bio::GMOD::CMap::Apache::HelpViewer:
    file: lib/Bio/GMOD/CMap/Apache/HelpViewer.pm
    version: 1.15
  Bio::GMOD::CMap::Apache::Index:
    file: lib/Bio/GMOD/CMap/Apache/Index.pm
    version: 1.9
  Bio::GMOD::CMap::Apache::LinkViewer:
    file: lib/Bio/GMOD/CMap/Apache/LinkViewer.pm
    version: 1.3
  Bio::GMOD::CMap::Apache::Login:
    file: lib/Bio/GMOD/CMap/Apache/Login.pm
    version: 1.2
  Bio::GMOD::CMap::Apache::MapSearch:
    file: lib/Bio/GMOD/CMap/Apache/MapSearch.pm
    version: 1.6
  Bio::GMOD::CMap::Apache::MapSetViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapSetViewer.pm
    version: 1.21
  Bio::GMOD::CMap::Apache::MapTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapTypeViewer.pm
    version: 1.8
  Bio::GMOD::CMap::Apache::MapViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapViewer.pm
    version: 1.121
  Bio::GMOD::CMap::Apache::MatrixViewer:
    file: lib/Bio/GMOD/CMap/Apache/MatrixViewer.pm
    version: 1.17
  Bio::GMOD::CMap::Apache::SavedLinkViewer:
    file: lib/Bio/GMOD/CMap/Apache/SavedLinkViewer.pm
  Bio::GMOD::CMap::Apache::SpeciesViewer:
    file: lib/Bio/GMOD/CMap/Apache/SpeciesViewer.pm
    version: 1.8
  Bio::GMOD::CMap::Apache::SpiderViewer:
    file: lib/Bio/GMOD/CMap/Apache/SpiderViewer.pm
    version: 1.4
  Bio::GMOD::CMap::Apache::ViewFeatureOnMap:
    file: lib/Bio/GMOD/CMap/Apache/ViewFeatureOnMap.pm
    version: 1.15
  Bio::GMOD::CMap::Config:
    file: lib/Bio/GMOD/CMap/Config.pm
  Bio::GMOD::CMap::Data:
    file: lib/Bio/GMOD/CMap/Data.pm
    version: 1.264
  Bio::GMOD::CMap::Data::Generic:
    file: lib/Bio/GMOD/CMap/Data/Generic.pm
    version: 1.129
  Bio::GMOD::CMap::Data::MySQL:
    file: lib/Bio/GMOD/CMap/Data/MySQL.pm
    version: 1.4
  Bio::GMOD::CMap::Data::Oracle:
    file: lib/Bio/GMOD/CMap/Data/Oracle.pm
    version: 1.6
  Bio::GMOD::CMap::Drawer:
    file: lib/Bio/GMOD/CMap/Drawer.pm
    version: 1.117
  Bio::GMOD::CMap::Drawer::Glyph:
    file: lib/Bio/GMOD/CMap/Drawer/Glyph.pm
    version: 1.11
  Bio::GMOD::CMap::Drawer::Map:
    file: lib/Bio/GMOD/CMap/Drawer/Map.pm
    version: 1.191
  Bio::GMOD::CMap::Utils:
    file: lib/Bio/GMOD/CMap/Utils.pm
    version: 1.66
generated_by: Module::Build version 0.22
