--- #YAML:1.0
name: cmap
version: 0.09
license: gpl
distribution_type: module
requires:
  Apache: 0
  Apache::Request: 0
  Class::Base: 0
  Config::General: 0
  DBI: 1.2
  Data::Page: 0
  Data::Pageset: 0
  File::MkTemp: 0
  GD: 1.33
  IO::Tee: 0
  Template: 2
  Text::RecordParser: 0.02
  Time::Object: 0
  Time::ParseDate: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Bio::GMOD::CMap:
    file: lib/Bio/GMOD/CMap.pm
    version: 0.09
  Bio::GMOD::CMap::Admin:
    file: lib/Bio/GMOD/CMap/Admin.pm
    version: 1.26
  Bio::GMOD::CMap::Admin::Import:
    file: lib/Bio/GMOD/CMap/Admin/Import.pm
    version: 1.33
  Bio::GMOD::CMap::Admin::ImportCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/ImportCorrespondences.pm
    version: 1.12
  Bio::GMOD::CMap::Admin::MakeCorrespondences:
    file: lib/Bio/GMOD/CMap/Admin/MakeCorrespondences.pm
    version: 1.22
  Bio::GMOD::CMap::Apache:
    file: lib/Bio/GMOD/CMap/Apache.pm
    version: 1.3
  Bio::GMOD::CMap::Apache::AdminViewer:
    file: lib/Bio/GMOD/CMap/Apache/AdminViewer.pm
    version: 1.45
  Bio::GMOD::CMap::Apache::FeatureSearch:
    file: lib/Bio/GMOD/CMap/Apache/FeatureSearch.pm
    version: 1.13
  Bio::GMOD::CMap::Apache::FeatureTypeViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureTypeViewer.pm
    version: 1.3
  Bio::GMOD::CMap::Apache::FeatureViewer:
    file: lib/Bio/GMOD/CMap/Apache/FeatureViewer.pm
    version: 1.8
  Bio::GMOD::CMap::Apache::HelpViewer:
    file: lib/Bio/GMOD/CMap/Apache/HelpViewer.pm
    version: 1.7
  Bio::GMOD::CMap::Apache::Index:
    file: lib/Bio/GMOD/CMap/Apache/Index.pm
    version: 1.5
  Bio::GMOD::CMap::Apache::MapDetailViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapDetailViewer.pm
    version: 1.19
  Bio::GMOD::CMap::Apache::MapSetViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapSetViewer.pm
    version: 1.10
  Bio::GMOD::CMap::Apache::MapViewer:
    file: lib/Bio/GMOD/CMap/Apache/MapViewer.pm
    version: 1.23
  Bio::GMOD::CMap::Apache::MatrixViewer:
    file: lib/Bio/GMOD/CMap/Apache/MatrixViewer.pm
    version: 1.5
  Bio::GMOD::CMap::Apache::ViewFeatureOnMap:
    file: lib/Bio/GMOD/CMap/Apache/ViewFeatureOnMap.pm
    version: 1.4
  Bio::GMOD::CMap::Data:
    file: lib/Bio/GMOD/CMap/Data.pm
    version: 1.61
  Bio::GMOD::CMap::Data::Generic:
    file: lib/Bio/GMOD/CMap/Data/Generic.pm
    version: 1.35
  Bio::GMOD::CMap::Data::MySQL:
    file: lib/Bio/GMOD/CMap/Data/MySQL.pm
    version: 1.2
  Bio::GMOD::CMap::Data::Oracle:
    file: lib/Bio/GMOD/CMap/Data/Oracle.pm
    version: 1.4
  Bio::GMOD::CMap::Drawer:
    file: lib/Bio/GMOD/CMap/Drawer.pm
    version: 1.44
  Bio::GMOD::CMap::Drawer::Map:
    file: lib/Bio/GMOD/CMap/Drawer/Map.pm
    version: 1.54
  Bio::GMOD::CMap::Utils:
    file: lib/Bio/GMOD/CMap/Utils.pm
    version: 1.22
generated_by: Module::Build version 0.20
