# vim: tw=70:

=pod

=head1 NAME

upgrade-15-to-16.pod

=head1 SYNOPSIS

Where we discuss updating CMap from version 0.15 to 0.16.

=head1 INTRODUCTION

Congratulations on your decision to upgrade from CMap version 0.15 to
0.16.  This guide will take you through upgrade.
 
This release does not change the database and only new options have
been added to the configuration files.  Therefor, you just need to
upgrade

Please make sure you back up both any template files that you may have
changed as well as your config files.  It is best not to take any
chances.

=head1 INSTALLING VERSION 0.16

Then run the build commands as you normally would 

 $ perl Build.PL
 $ ./Build
 $ su
 # ./Build install

Make sure the new template files have been added by doing a 

 # cp -f templates/*.tmpl /usr/local/apache/templates/cmap/

=head1 DATABASE UPDATE

There are no database changes in this release.

=head1 CONFIGURATION FILE UPDATE

There are no required configuration changes in this release.  Please
see the ADMINISTRATION.pod for further information on config options.

=head1 CONCLUSION

That should do it for the upgrade process.  If you have any troubles
email the CMap developer's list:

  gmod-cmap@lists.sourceforge.net

Please see the CMap home page (http://www.gmod.org/cmap/index.shtml)
for other information and patches.

=head1 AUTHOR

Ben Faga E<lt>faga@cshl.eduE<gt>.

=cut
