package CSHL::CMap::Apache::HelpViewer;

# $Id: HelpViewer.pm,v 1.1.1.1 2002-07-31 23:27:28 kycl4rk Exp $

use strict;
use vars qw( $VERSION );
$VERSION = (qw$Revision: 1.1.1.1 $)[-1];

use Apache::Constants;

use CSHL::CMap::Apache;
use base 'CSHL::CMap::Apache';

use constant TEMPLATE => 'help.tmpl';

sub handler {
    #
    # Make a jazz noise here...
    #
    my ( $self, $apr ) = @_;

    my $html;
    my $t = $self->template;
    $t->process( TEMPLATE, { page => $self->page }, \$html ) 
        or $html = $t->error;

    $apr->content_type('text/html');
    $apr->send_http_header;
    $apr->print( $html );
    return OK;
}

1;

# ----------------------------------------------------
# A burnt child loves the fire.
# Oscar Wilde
# ----------------------------------------------------

=head1 NAME

CSHL::CMap::Apache::HelpViewer - show help

=head1 SYNOPSIS

In httpd.conf:

  <Location /cmap/help>
      SetHandler  perl-script
      PerlHandler CSHL::CMap::Apache::HelpViewer->super
  </Location>

=head1 DESCRIPTION

Displays the user help document for the maps. It's actually a minimal handler
that does little more than display an static HTML page. The reason the user
help isn't just static HTML is because it was deemed necessary to include the
help in other pages generated by Template Toolkit; therefore, the HTML was
moved into a template file in the "templates" directory so that Template
Toolkit could find and use it easily.

=head1 SEE ALSO

L<perl>.

=head1 AUTHOR

Ken Y. Clark E<lt>kclark@cshl.orgE<gt>

Copyright (c) 2002 Cold Spring Harbor Laboratory

This library is free software;  you can redistribute it and/or modify 
it under the same terms as Perl itself.

=cut
