#!/usr/bin/env perl

use strict;
use if $ENV{'CMAP_ROOT'}, lib => $ENV{'CMAP_ROOT'} . '/lib';
use Bio::GMOD::CMap::Apache;

# To use a config directory other than the default,
# call handler with the config_dir argument.
# Bio::GMOD::CMap::Apache::handler( config_dir => '/path/to/cmap.conf' );
eval { Bio::GMOD::CMap::Apache::handler(); };

if ( my $err = $@ ) {
    print "Content-type: text/plain\n\nError: $err";
}
